version: '3'
services:
  db:
    image: mysql:5.6.36
    container_name: mysql5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: test
      MYSQL_PASSWORD: test01
      MYSQL_DATABASE: playground
    volumes:
      - ./conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
